name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]

    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/build.yaml
          channels: conda-forge,nodefaults
          activate-environment: conda-build
          use-mamba: true
          miniforge-variant: Mambaforge
          
      - name: copy and prepare recipe
        run: make prepare-recipe

      - name: conda build
        run: make conda-build

      - name: publish conda package
        env: # Or as an environment variable
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        if: ${{ success() && (github.event_name == 'push' || github.event_name == 'schedule') }}
        run: |
          anaconda --token $ANACONDA_TOKEN upload --user opensciencelabs --skip-existing /usr/share/miniconda/envs/llvmdev/conda-bld/linux-64/llvmdev-dbg*.tar.bz2
